### ISSUE TITLE
Однотипный код

### ISSUE THREAD

**Issue by jawello** [ProdavecBurrito/OOPFirst#3]
https://github.com/ProdavecBurrito/OOPFirst/blob/9723e352623f82dca954c2fbb51ddd9b75c3ea50/Character.cs#L82-L115

Тут явно однотипный код. Можно вынести в отдельный метод. А то индусами пахнет

**Comment by ProdavecBurrito** [comment]
понял

**Comment by ProdavecBurrito** [comment]
поправил. все в пулл-реквесте
