### ISSUE TITLE
В классе Object код, который не относится к Object'у

### ISSUE THREAD

**Issue by jawello** [ProdavecBurrito/OOPFirst#4]
https://github.com/ProdavecBurrito/OOPFirst/blob/9723e352623f82dca954c2fbb51ddd9b75c3ea50/Object.cs#L24-L95

В данном классе есть конструкторы, которые нужны Barriers.cs, есть методы, которые нужны Barrier.cs. При этом кучу классов наследуются от класса Object, т.е. они наследуют функциональность, которая нужна только Barriers.cs. Вопрос - зачем все это в классе Object? 

В Object нужно оставить, только то что, нужно всем! по сути это координаты и символ, которым отображается,  конструктор, который это получает на вход и метод отображения.

**Comment by ProdavecBurrito** [comment]
примерно понял

**Comment by ProdavecBurrito** [comment]
полнотью переделал это дело. удалил код, отвечающий за класс Elixir в сам класс Elixir, , удалил лишние классы Barrier и переименовал Object в Barrier. В пулл-реквесте
