### ISSUE TITLE
Игровая логика внутри персонажа

### ISSUE THREAD

**Issue by jawello** [ProdavecBurrito/OOPFirst#5]
https://github.com/ProdavecBurrito/OOPFirst/blob/9723e352623f82dca954c2fbb51ddd9b75c3ea50/Character.cs#L251-L312

У тебя внутри персонажа собрана логика, которая не имеет к нему отношения. Вывод статуса, вывод сообщений о победе или проигрыше. 

Класс - сущность, которая отвечает строго за определенный кусок функциональности. А у тебя функциональность запихивается в класс по другому принципу.

**Comment by ProdavecBurrito** [comment]
оке, попробую поправить

**Comment by ProdavecBurrito** [comment]
поправил (только вот вопрос - правильно ли). в пулл-реквесте

**Comment by ProdavecBurrito** [comment]
Еще не согласен про "статус". это же напрямую к его состоянию относится - значит, часть перса, нет?

**Comment by jawello** [comment]
Статус - да, это относится к персу. Но не вывод в консоль) Pull request гляну
