### ISSUE TITLE
Нет разделения логики и интерфейса

### ISSUE THREAD

**Issue by jawello** [ProdavecBurrito/OOPFirst#6]
https://github.com/ProdavecBurrito/OOPFirst/blob/9723e352623f82dca954c2fbb51ddd9b75c3ea50/Character.cs#L242-L246

Все что касается класса Console - это интерфейс! Потому что с помощью этого класса ты взаимодействуешь с экраном. Представь, что теперь тебе надо выводить все не в консоль, а в юнити. Тебе придется переделать весь свой код! Хорошая архитектура подразумевает, что при смене пользовательского интерфейса тебе надо будет все поменять в одном классе, который отвечает за вывод на экран. У тебя не хватает такой прослойки. 

Но честно скажу - это не тривиальная задача, и на первой программе ООП хрен сделаешь нормально. Но стремиться можешь.

Если не понимаешь как сделать нормально, то запиши в вопросы - и я покажу на уроке пример.

**Comment by ProdavecBurrito** [comment]
Записал
